# -*- coding: utf-8 -*-
"""Mistral7B-MedMCQA-QLoRA-unsloth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFg766HRP4_Wr05spQspeBfHTdO1vgCm
"""

# !pip install torch==2.9.0

# !pip install -q unsloth

# from google.colab import drive
# drive.mount("/content/drive")

from data_loader import train_data, instruction_tuned_dataset, valid_data
from model_loader import load_model, load_model_for_inference
from trainer import define_trainer
from inference import calculate_acc

from huggingface_hub import notebook_login
notebook_login()

data = train_data('data/train.json')
dataset = instruction_tuned_dataset(data)

model, tokenizer = load_model()
trainer = define_trainer()
trainer_stats = trainer.train()
trainer.push_to_hub()

val_data = valid_data()
model, tokenizer = load_model_for_inference()
accuracy = calculate_acc(val_data, model, tokenizer)
print(f'Accuracy : {accuracy}')